import type { Metadata } from 'next';
import { Open_Sans, Rubik } from 'next/font/google';
import './globals.css';
// import Providers from './ui/Provider';

const openSans = Open_Sans({ subsets: ['latin'],  variable: '--font-opensans', })

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <Providers>
      <html lang="en">
        <body className={`${openSans.variable} ${rubik.variable} font-rubik`}>{children}</body>
      </html>
    // </Providers>
  )
}
